In [8]:
#Library Import and Missing value Handling 

import numpy as np
import pandas as pd
from sklearn.preprocessing import Imputer

df = pd.read_csv('cancer.csv')
df.replace('?',0, inplace=True)
#print((df[[6]] == 0).sum())

df[[6]] = df[[6]].replace(0, np.NaN)
# Fill missing values with mean column values
values = df.values
imputer = Imputer()
transformed_values = imputer.fit_transform(values)
# Count the number of NaN values in each column
print(np.isnan(transformed_values).sum())

0

In [9]:
# Making a dataframe and saving it
preprocessed_df = pd.DataFrame(data = transformed_values)
preprocessed_df.to_csv('Preprocessed.csv')

In [17]:
# Load the preprocessed dataset 

dataframe = pd.read_csv('Preprocessed.csv')
#dataframe

# Drop the ID i.e. 0th Column

dataframe.drop(dataframe.columns[[0]],axis = 1, inplace = True)

In [18]:
dataframe

      1   2   3   4  5          6   7   8  9  10
0     5   1   1   1  2   1.000000   3   1  1   2
1     5   4   4   5  7  10.000000   3   2  1   2
2     3   1   1   1  2   2.000000   3   1  1   2
3     6   8   8   1  3   4.000000   3   7  1   2
4     4   1   1   3  2   1.000000   3   1  1   2
5     8  10  10   8  7  10.000000   9   7  1   4
6     1   1   1   1  2  10.000000   3   1  1   2
7     2   1   2   1  2   1.000000   3   1  1   2
8     2   1   1   1  2   1.000000   1   1  5   2
9     4   2   1   1  2   1.000000   2   1  1   2
10    1   1   1   1  1   1.000000   3   1  1   2
11    2   1   1   1  2   1.000000   2   1  1   2
12    5   3   3   3  2   3.000000   4   4  1   4
13    1   1   1   1  2   3.000000   3   1  1   2
14    8   7   5  10  7   9.000000   5   5  4   4
15    7   4   6   4  6   1.000000   4   3  1   4
16    4   1   1   1  2   1.000000   2   1  1   2
17    4   1   1   1  2   1.000000   3   1  1   2
18   10   7   7   6  4  10.000000   4   1  2   4
19    6   1   1   1  2   1.000000   3   1  1   2
20    7   3   2  10  5  10.000000   5   4  4   4
21   10   5   5   3  6   7.000000   7  10  1   4
22    3   1   1   1  2   1.000000   2   1  1   2
23    8   4   5   1  2   3.544656   7   3  1   4
24    1   1   1   1  2   1.000000   3   1  1   2
25    5   2   3   4  2   7.000000   3   6  1   4
26    3   2   1   1  1   1.000000   2   1  1   2
27    5   1   1   1  2   1.000000   2   1  1   2
28    2   1   1   1  2   1.000000   2   1  1   2
29    1   1   3   1  2   1.000000   1   1  1   2
..   ..  ..  ..  .. ..        ...  ..  .. ..  ..
669   5  10  10   8  5   5.000000   7  10  1   4
670   3  10   7   8  5   8.000000   7   4  1   4
671   3   2   1   2  2   1.000000   3   1  1   2
672   2   1   1   1  2   1.000000   3   1  1   2
673   5   3   2   1  3   1.000000   1   1  1   2
674   1   1   1   1  2   1.000000   2   1  1   2
675   4   1   4   1  2   1.000000   1   1  1   2
676   1   1   2   1  2   1.000000   2   1  1   2
677   5   1   1   1  2   1.000000   1   1  1   2
678   1   1   1   1  2   1.000000   1   1  1   2
679   2   1   1   1  2   1.000000   1   1  1   2
680  10  10  10  10  5  10.000000  10  10  7   4
681   5  10  10  10  4  10.000000   5   6  3   4
682   5   1   1   1  2   1.000000   3   2  1   2
683   1   1   1   1  2   1.000000   1   1  1   2
684   1   1   1   1  2   1.000000   1   1  1   2
685   1   1   1   1  2   1.000000   1   1  1   2
686   1   1   1   1  2   1.000000   1   1  1   2
687   3   1   1   1  2   1.000000   2   3  1   2
688   4   1   1   1  2   1.000000   1   1  1   2
689   1   1   1   1  2   1.000000   1   1  8   2
690   1   1   1   3  2   1.000000   1   1  1   2
691   5  10  10   5  4   5.000000   4   4  1   4
692   3   1   1   1  2   1.000000   1   1  1   2
693   3   1   1   1  2   1.000000   2   1  2   2
694   3   1   1   1  3   2.000000   1   1  1   2
695   2   1   1   1  2   1.000000   1   1  1   2
696   5  10  10   3  7   3.000000   8  10  2   4
697   4   8   6   4  3   4.000000  10   6  1   4
698   4   8   8   5  4   5.000000  10   4  1   4

[699 rows x 10 columns]

In [19]:
# Normalize the Dataset
from sklearn.preprocessing import MinMaxScaler

array = dataframe.values
scaler = MinMaxScaler(feature_range=(0, 1))
normalized_array = scaler.fit_transform(array)

In [21]:
normalized_array.shape

(699, 10)

Ensembles in Action

In [22]:
# Bagged Decision Trees for Classification

from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

array = normalized_array
X = array[:,0:9]
Y = array[:,9]
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cart = DecisionTreeClassifier()
num_trees = 100
model = BaggingClassifier(base_estimator=cart, n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.961428571429

In [23]:
# AdaBoost Classification

from sklearn.ensemble import AdaBoostClassifier
seed = 7
num_trees = 30
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = AdaBoostClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.95281573499

In [24]:
# Stochastic Gradient Boosting Classification

from sklearn.ensemble import GradientBoostingClassifier

seed = 7
num_trees = 100
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = GradientBoostingClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.96

In [25]:
# Voting Ensemble for Classification

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

kfold = model_selection.KFold(n_splits=10, random_state=seed)
# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('logistic', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))
# create the ensemble model
ensemble = VotingClassifier(estimators)
results = model_selection.cross_val_score(ensemble, X, Y, cv=kfold)
print(results.mean())

0.962857142857